version: "3.3"

services:
  server:
    container_name: small-chat-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - small-chat-server-node-modules:/app/node_modules

volumes:
  small-chat-server-node-modules:
