FROM golang:1.19.1-alpine3.16

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY server/go.mod server/go.sum ./

# RUN go get -u github.com/gin-gonic/gin

# 依存関係のダウンロード
RUN go mod download

COPY /server .

CMD ["air", "-c", ".air.toml"]
# CMD [ "go", "run", "main.go" ]